apiVersion: v1
kind: Pod
metadata:
  name: counting-service-deployment
spec:
  containers:
  - name: counting-service
    image: topfunky/counting-service:0.0.1
    ports:
    - containerPort: 9001
  initContainers:
  - name: counting-init
    image: topfunky/counting-init:0.0.9
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
